import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * 整个侧边栏由 docs/ 目录结构自动生成。
 *
 * 不手工列举页面，是因为迁移会一次性带入 97 页，逐页登记既冗长又容易与实际
 * 文件脱节。顺序由各页 frontmatter 的 sidebar_position 与每个章节目录下的
 * _category_.json 控制：根级页占 1、2、99，12 个章节占 10–21，互不穿插。
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
