/**
 * 一次性迁移脚本：dumi docs-dumi/ → Docusaurus docs/
 *
 * 只做机械转换，不生成任何内容文字：
 *   - 目录名 snake_case → kebab-case，与规格 §7.2 的新 URL 一致
 *   - 文件名 Snake_Case → kebab-case
 *   - frontmatter：order → sidebar_position；group.title 由 _category_.json 承载
 *   - 丢弃 dumi 专有键：group、nav、hero、features、keywords
 *   - description 为空时写入 DESCRIPTION_PLACEHOLDER，由人工逐页补写；
 *     留占位而非留空，是为了让 grep 能一眼列出待办页面。
 *
 * 保留此脚本是为了迁移结果可复核、可重跑。
 */
import fs from 'node:fs/promises'
import path from 'node:path'

// 骨架任务已把 dumi 内容整体移到 docs-dumi/，docs/ 下现在只有一个占位页。
const SRC = 'docs-dumi'
const OUT = 'docs-migrated'

export const DESCRIPTION_PLACEHOLDER = 'TODO_DESCRIPTION'

/** dumi 目录名 → Docusaurus 目录名，与规格 §7.2 逐条对应。 */
const SECTION_DIRS = {
  shapes: 'shapes',
  styling: 'styling',
  events: 'events',
  drag_and_drop: 'drag-and-drop',
  clipping: 'clipping',
  groups_and_layers: 'groups-and-layers',
  filters: 'filters',
  tweens: 'tweens',
  animations: 'animations',
  selectors: 'selectors',
  data_and_serialization: 'data-and-serialization',
  performance: 'performance',
}

/**
 * 章节标题沿用原 dumi frontmatter 的 group.title，相对顺序沿用 group.order。
 *
 * position 从 10 起算而非 1：侧边栏由 autogenerated 生成，根级页
 * （intro=1、overview=2、support=99）与章节共用同一个排序序列。
 * 若章节仍用 1–12，会和 intro/overview 相互穿插。
 */
const CATEGORY_LABELS = {
  shapes: { label: '图形', position: 10 },
  styling: { label: '样式', position: 11 },
  events: { label: '事件', position: 12 },
  'drag-and-drop': { label: '拖拽/释放', position: 13 },
  clipping: { label: '剪辑', position: 14 },
  'groups-and-layers': { label: '分组、图层', position: 15 },
  filters: { label: '滤镜', position: 16 },
  tweens: { label: '补间动画', position: 17 },
  animations: { label: '动画', position: 18 },
  selectors: { label: '选择器', position: 19 },
  'data-and-serialization': { label: '数据序列化', position: 20 },
  performance: { label: '性能优化', position: 21 },
}

/** Snake_Case / CamelCase 文件名 → kebab-case，与规格 §7.2 的 clean_slug 规则一致。 */
export function kebab(name) {
  let s = name.replace(/([a-z0-9])([A-Z])/g, '$1-$2')
  s = s.replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
  return s.replace(/_/g, '-').toLowerCase().replace(/-+/g, '-').replace(/^-|-$/g, '')
}

function parseFrontmatter(text) {
  const m = /^---\n([\s\S]*?)\n---\n?/.exec(text)
  if (!m) return { fm: {}, body: text }
  const fm = {}
  // 只取顶层 key，缩进行（group/nav/hero/features 的子项）自然被跳过。
  for (const line of m[1].split('\n')) {
    const kv = /^([a-zA-Z_]+):\s*(.*)$/.exec(line)
    if (kv) fm[kv[1]] = kv[2].trim()
  }
  return { fm, body: text.slice(m[0].length) }
}

function yamlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

async function emit(outPath, fm, body) {
  const lines = ['---']
  for (const [k, v] of Object.entries(fm)) {
    if (v === undefined || v === null || v === '') continue
    lines.push(`${k}: ${typeof v === 'number' ? v : yamlString(v)}`)
  }
  lines.push('---', '')
  await fs.mkdir(path.dirname(outPath), { recursive: true })
  await fs.writeFile(outPath, lines.join('\n') + body.replace(/^\n+/, '\n'))
}

function pickDescription(fm) {
  return fm.description && fm.description !== "''" && fm.description !== '""'
    ? fm.description.replace(/^['"]|['"]$/g, '')
    : DESCRIPTION_PLACEHOLDER
}

async function main() {
  await fs.rm(OUT, { recursive: true, force: true })
  let count = 0

  // 三个根级页面单独处理，目标路径由规格 §7.2 指定。
  const roots = [
    { src: 'start/index.md', out: 'intro.md', position: 1 },
    { src: 'guides/index.md', out: 'overview.md', position: 2 },
    { src: 'help/index.md', out: 'support.md', position: 99 },
  ]
  for (const r of roots) {
    const text = await fs.readFile(path.join(SRC, r.src), 'utf8')
    const { fm, body } = parseFrontmatter(text)
    await emit(
      path.join(OUT, r.out),
      { title: fm.title, description: pickDescription(fm), sidebar_position: r.position },
      body
    )
    count++
  }

  // 12 个章节
  for (const [srcDir, outDir] of Object.entries(SECTION_DIRS)) {
    const dir = path.join(SRC, 'guides', srcDir)
    const files = (await fs.readdir(dir)).filter((f) => f.endsWith('.md'))
    for (const f of files) {
      const text = await fs.readFile(path.join(dir, f), 'utf8')
      const { fm, body } = parseFrontmatter(text)
      await emit(
        path.join(OUT, outDir, `${kebab(f.replace(/\.md$/, ''))}.md`),
        { title: fm.title, description: pickDescription(fm), sidebar_position: Number(fm.order) || 1 },
        body
      )
      count++
    }
    const cat = CATEGORY_LABELS[outDir]
    await fs.writeFile(
      path.join(OUT, outDir, '_category_.json'),
      JSON.stringify({ label: cat.label, position: cat.position }, null, 2) + '\n'
    )
  }

  console.log(`迁移完成：${count} 页 → ${OUT}/`)
}

main()
